### ISSUE TITLE
App crashed when Hide/Sleep (Android < 5.0.0)

### ISSUE THREAD

**Issue by LucasNova** [Esri/cordova-plugin-advanced-geolocation#15]
Hello, i know you write application for 5.0.0, but on many devices lower version your plugin is work. Unfortunately i can't use this on production, becouse plugin crash my app when user want to hide application or application just sleep. Please resolve an issue, at least make try...catch, ty.

**Comment by andygup** [comment]
Hi @LucasNova the main challenge is I don't have a < 5.x phone to do any testing so I'm unable to try and replicate an issues you may be seeing. 

I can certainly look into disabling certain functionality when it's not supported by the phone. For example, using Cellular Data calls the native method [TelephonyManager.getAllCellInfo()](https://developer.android.com/reference/android/telephony/TelephonyManager.html#getAllCellInfo()) which explicitly requires API 17 or greater. 

1) Please provide the native Android error dump from when the app crashes. This will tell us exactly where the problem is occurring. Use Android Studio to access the [Android ADB debugging information](https://developer.android.com/studio/debug/index.html).

2) Provide an example of your `AdvancedGeolocation` configuration options. Example:

```js
{
        "minTime":500,         // Min time interval between updates (ms)
        "minDistance":1,       // Min distance between updates (meters)
        "noWarn":true,         // Native location provider warnings
        "providers":"all",     // Return GPS, NETWORK and CELL locations
        "useCache":true,       // Return GPS and NETWORK cached locations
        "satelliteData":false, // Return of GPS satellite info
        "buffer":false,        // Buffer location data
        "bufferSize":0         // Max elements in buffer
    }

```
