### ISSUE TITLE
ANR issue onDestroy?

### ISSUE THREAD

**Issue by junbonglee** [Esri/cordova-plugin-advanced-geolocation#68]
![2018-11-29 17 51 00](https://user-images.githubusercontent.com/10484267/49210183-cd37db00-f3ff-11e8-860a-2273b53a0f62.png)
![2018-11-29 19 49 06](https://user-images.githubusercontent.com/10484267/49217036-dc268980-f40f-11e8-8669-6c3c431d36a1.png)

Thank you for the great plugin. I'm having an ANR issue, and the image is screenshot of related ANR from Google Play Console.

I think it's shutdownAndAwaitTermination function causing the ANR, and wondering if terminating threadpool onDestroy is neccessary. If it's not, Is it ok to comment out 

shutdownAndAwaitTermination(_cordova.getThreadPool());
_cordovaActivity.finish();

these two function inside onDestroy()?

I am worried if commenting out these two will cause another problem.

**Comment by andygup** [comment]
@junbonglee I'd say go ahead and comment it out and test it. Reference: https://github.com/Esri/cordova-plugin-advanced-geolocation/blob/master/src/com/esri/cordova/geolocation/AdvancedGeolocation.java#L446

The general reason that's code is in there is because of multiple issues where Cordova's shutdown code didn't work properly and probably still doesn't handle internal thread pooling very well. Cordova used to not correctly checking for `Thread.currentThread().isInterrupted()` and that's also caused a variety of issues with other plugins, reference: https://github.com/Esri/cordova-plugin-advanced-geolocation/issues/49#issuecomment-384719552

**Comment by andygup** [comment]
I'm closing this out, if something else comes up feel free to ping me.
